# Generated by Django 4.2.5 on 2024-05-23 09:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_en', models.CharField(max_length=100)),
                ('name_lc', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('apiid', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'mst_countries',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_en', models.CharField(max_length=100)),
                ('name_lc', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apiid', models.CharField(max_length=50, null=True)),
                ('gps_lat', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('gps_long', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'mst_districts',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('from_date_bs', models.CharField(max_length=10)),
                ('from_date_ad', models.DateField()),
                ('to_date_bs', models.CharField(max_length=10)),
                ('to_date_ad', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mst_fiscal_years',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_en', models.CharField(max_length=100)),
                ('name_lc', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mst_genders',
            },
        ),
        migrations.CreateModel(
            name='NepaliMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_en', models.CharField(max_length=100)),
                ('name_lc', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mst_nepali_months',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_en', models.CharField(max_length=100)),
                ('name_lc', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apiid', models.CharField(max_length=50, null=True)),
                ('gps_lat', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('gps_long', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'mst_provinces',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='LocalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_en', models.CharField(max_length=100)),
                ('name_lc', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apiid', models.CharField(max_length=50, null=True)),
                ('wards_count', models.IntegerField(null=True)),
                ('gps_lat', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('gps_long', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.district')),
            ],
            options={
                'db_table': 'mst_local_levels',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.province'),
        ),
    ]
